### PR TITLE
Update tests.py with item hold

### PR DESCRIPTION
**Pull request by paramsangani**
added another test case for get item from id and then added 2 test cases for item on hold. Need to check if they fail

### CODE REVIEW

**Comment by loganwyas** [comment]
@paramsangani If you want to see whether your tests fail or not, it's probably better to run on your local machine. The CircleCI pipeline only works on select branches.

**Comment by paramsangani** [comment]
> @paramsangani If you want to see whether your tests fail or not, it's probably better to run on your local machine. The CircleCI pipeline only works on select branches.

**Comment by paramsangani** [comment]
@loganwyas Got it, so will I have to create another test.py file to test these?

**Comment by loganwyas** [comment]
@paramsangani Nope, you should just be able to run pytest on your computer and it will work. You can look at the CircleCI pipeline if you need to know how to run pytest.

**Pull request closed without merging**
